### ISSUE TITLE
El campo dirección reconoce el carácter "ñ" como error

### ISSUE THREAD

**Issue by geronm12** [hectorc2907/RollingPaws-FrontEnd#10]
### SITUACION ACTUAL
Ingresar a la app como un usuario registrado previamente. 
Dirigirse a la solapa de agregar/modificar.
Rellenar los campos y en el campo dirección colcar alguna dirección con letra ñ 

![image](https://github.com/hectorc2907/RollingPaws-FrontEnd/assets/44532299/f2a016b7-d6ef-4d98-a3b9-6c081bacb40d)

**RESULTADO OBTENIDO**
No deja enviar el fomulario  ya que reconoce el carácter ñ como un carácter especial.

**RESULTADO ESPERADO** 
Esto va a ser válido o no dependiendo de la cultura. Al ser una página en español debería tomar la letra Ñ.

**Comment by hectorc2907** [comment]
se realiza la corrección de la expresión regular para que el formulario acepte la letra ñ
