### ISSUE TITLE
Campo Teléfono debería mostrar un mensaje de error 

### ISSUE THREAD

**Issue by geronm12** [hectorc2907/RollingPaws-FrontEnd#11]
### SITUACION ACTUAL
Ingresar a la app como un usuario registrado. Dirigirse a agregar un paciente, rellenar todos los campos y en campo teléfono colocar un sólo dígito. Hacer click en generar.

https://github.com/hectorc2907/RollingPaws-FrontEnd/assets/44532299/a4bc2a4a-019a-4a44-82ca-ed9d207d61ea

**RESULTADO OBTENIDO**
No envia el formulario y le hace foco al campo dirección

**RESULTADO ESPERADO**
El no envio del formulario es correcto pero es necesario que se le muestre un label al usuario indicando el error y ofreciendo una solución para poder resolver dicho error

**Comment by hectorc2907** [comment]
se realiza la corrección de un dato mal escrito, este se encuentra en el form.text, este tenia escrito numeroDuenio, se cambia por telefonoDuenio para que el mensaje pueda presentarse en caso de no cumplir sus condiciones
