### ISSUE TITLE
Cambiar Veterinarios

### ISSUE THREAD

**Issue by geronm12** [hectorc2907/RollingPaws-FrontEnd#13]
### SITUACION ACTUAL
Ingresar a la app como un usuario registrado y hacer click en "agregar turno".

![image](https://github.com/hectorc2907/RollingPaws-FrontEnd/assets/44532299/316973a4-c65d-4256-b40e-ccbe9858068d)

**RESULTADO OBTENIDO**
En el dropdown veremos la lista que indica "veterinario 1", "2","3", etc.

**RESULTADO ESPERADO**
NUNCA debe subirse a producción un sistema con datos mal hardcodeados. "veterinario 1", "veteriario 2" o "veterinario 3" debería tener nombres. Si se va a hacer una demo con un cliente no se puede presentar así.  Tengan cuidado con este tipo de cosas chicos!

**Comment by hectorc2907** [comment]
se realiza la corrección para que se agregue nombres de doctores y nos opciones genéricas
