### ISSUE TITLE
Error al importar fuente

### ISSUE THREAD

**Issue by geronm12** [hectorc2907/RollingPaws-FrontEnd#7]
Este issue también lo levanto más informal, está mandando un error a la consola del navegador. Al parecer se intenta importar una fuente y lo imprime en consola. 

![image](https://github.com/hectorc2907/RollingPaws-FrontEnd/assets/44532299/0107c4ee-81e6-4526-a630-3a28a803f4d9)

Para resolverlo pueden catchear diferente el error (manejarlo de otra forma) o si no están usando esa fuente pueden quitar la referencia a la misma.

**Comment by hectorc2907** [comment]
se corrigen en el app.css las fuentes, se borra una porción de código que generaba el fallo, pero no afecto a la fuente que se muestra
