### ISSUE TITLE
Eliminar console.log al iniciar sesión

### ISSUE THREAD

**Issue by geronm12** [hectorc2907/RollingPaws-FrontEnd#8]
### SITUACTION ACTUAL
con un usuario registrado dirigirse a la pestaña de login e ingresar las credenciales para el inicio de sesión

**RESULTADO OBTENIDO**
Inicia sesión correctamente pero muestra el log de los datos del usuario en la consola

![image](https://github.com/hectorc2907/RollingPaws-FrontEnd/assets/44532299/14eb25a9-9ea0-4cfd-bfe8-dc8c06423f4c)

**RESULTADO ESPERADO**
la consola debería permanecer limpia en todo momento

**Comment by hectorc2907** [comment]
se elimina el log del login para no imprimir datos de inicio de sesión
